blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archievs'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url('about', views.about, name='about')
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk':self.pk})
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    
    class Meta:
        ordering = ['-created_time']


    '''
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:50]
        
        super(Post, self).save(*args, **kwargs)
        '''

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post, Category
import markdown

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 2

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                            created_time__month=month)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    #Override get() to increase num of view in Post
    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response
    
    #content to markdown
    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body, extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
        return post
    
'''
def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })
'''
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    post.body = markdown.markdown(post.body, extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    return render(request, 'blog/detail.html', context={'post':post})

def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list':post_list})

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list':post_list})

def about(request):
    return render(request, 'blog/about.html', context={})

templates/base.html
{% load staticfiles %} {% load blog_tags %}
<!DOCTYPE html>
<html>

<head>
    <title>Patrick's rockhouse</title>

    <!-- icon -->
    <link rel="icon" href="{% static 'blog/img/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}" type="image/x-icon" />

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

    <!-- Google Analytics -->
    <script>
        (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-113447096-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->


</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1>
                            <a href="{% url 'blog:index' %}">
                                <b>Patrick's</b> rockhouse</a>
                        </h1>
                    </div>
                </div>
                <!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:index' %}" data-hover="首页">首页</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:index' %}" data-hover="博客">博客</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:about' %}" data-hover="关于">关于</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="mailto:cirillaye@outlook.com" data-hover="联系">联系</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#">
                            <span id="search-icon" class="ion-ios-search-strong"></span>
                        </a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit">
                                    <span class="ion-ios-search-strong"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- col-md-8 -->
            </div>
        </header>
    </div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %} {% endblock main %}
                </main>
                <aside class="col-md-4 aside">
                    <div class="aside">
                        {% block toc %} {% endblock toc %}
                        <div class="widget widget-recent-posts">
                            <h3 class="widget-title">最新</h3>
                            {% get_recent_posts as recent_post_list %}
                            <ul>
                                {% for post in recent_post_list %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </li>
                                {% empty %}
                                <li>
                                    not yet
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget widget-archives">
                            <h3 class="widget-title">归档</h3>
                            {% archives as date_list %}
                            <ul>
                                {% for date in date_list %}
                                <li>
                                    <a href="{% url 'blog:archievs' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                                </li>
                                {% empty %}
                                <li>
                                    not yet
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

                        <div class="widget widget-category">
                            <h3 class="widget-title">分类</h3>
                            {% get_category as category_list %}
                            <ul>
                                {% for category in category_list %}
                                <li>
                                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                                {% empty %}
                                <li>
                                    not yet
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                -->
                        <div class="rss">
                            <a href="">
                                <span class="ion-social-rss-outline"></span> RSS 订阅</a>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2017 Yukai Song
                        <br>Blog theme modified from Black & White, Designed by Technext Limited
                    </p>

                </div>
            </div>
        </div>
    </footer>


    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close">
            <span class="ion-ios-close-empty"></span>
        </button>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'blog:index' %}">首页</a>
                </li>
                <li>
                    <a href="{% url 'blog:index' %}">博客</a>
                </li>
                <li>
                    <a href="{% url 'blog:about' %}">关于</a>
                </li>
                <li>
                    <a href="mailto:cirillaye@outlook.com">联系</a>
                </li>
            </ul>
        </nav>
    </div>

    <script src="{% static 'blog/js/script.js' %}"></script>

</body>

</html>

templates/blog/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <title>Patrick's rockhouse</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body id="page">
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1>
                            <a href="{% url 'blog:index' %}">
                                <b>Patrick's</b> rockhouse</a>
                        </h1>
                    </div>
                </div>
                <!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:index' %}" data-hover="首页">首页</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:index' %}" data-hover="博客">博客</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="{% url 'blog:about' %}" data-hover="关于">关于</a>
                                </li>
                                <li class="cl-effect-11">
                                    <a href="mailto:cirillaye@outlook.com" data-hover="联系">联系</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#">
                            <span id="search-icon" class="ion-ios-search-strong"></span>
                        </a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit">
                                    <span class="ion-ios-search-strong"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- col-md-8 -->
            </div>
        </header>
    </div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    
                    <article class="post">
                        <div class="entry-content clearfix">
                            <h1 class="page-title">貝殼街 120 號</h1>
                            <figure class="img-responsive-center">
                                <img class="img-responsive" src="{% static 'blog/img/InsidePats.jpg' %}" alt="house">
                            </figure>

                            <div class="height-40px"></div>
                            <h2 class="title text-center">Social</h2>
                            <ul class="social">
                                <li class="facebook">
                                    <a href="#">
                                        <span class="ion-social-facebook"></span>
                                    </a>
                                </li>
                                <li class="twitter">
                                    <a href="#">
                                        <span class="ion-social-twitter"></span>
                                    </a>
                                </li>
                                <li class="google-plus">
                                    <a href="#">
                                        <span class="ion-social-googleplus"></span>
                                    </a>
                                </li>
                                <li class="tumblr">
                                    <a href="#">
                                        <span class="ion-social-tumblr"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2017 Yukai Song
                        <br>Blog theme modified from Black & White, Designed by Technext Limited
                    </p>

                </div>
            </div>
        </div>
    </footer>


    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close">
            <span class="ion-ios-close-empty"></span>
        </button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="{% url 'blog:index' %}">博客</a></li>
                <li><a href="{% url 'blog:about' %}">关于</a></li>
                <li><a href="mailto:cirillaye@outlook.com">联系</a></li>
            </ul>
        </nav>
    </div>

    <script src="{% static 'blog/js/script.js' %}"></script>


</body>

</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
    
    <article class="detail">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">分类 {{ post.category }}</a></span>
                
                <span class="post-author"><a href="#">作者 {{ post.author }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                    datetime="{{ post.created_time }}">{{ post.created_time|date:"Y-m-d" }}</time></a></span>
                <span class="post-author"><a href="#">阅读 {{ post.views }}</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
        
    </article>
    <section>
        <div id="alertWall" class="alert alert-danger" role="alert" style="display:none;">
            Lord I'm five hundred miles from Disqus
        </div>
        <div id="disqus_thread"></div>
        <script src="{% static 'blog/js/disqus_onload.js' %}"></script>
        <!--
        <script>
        
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://soongyk-com.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        --> 
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                               
    </section>
    <!-- City版安装代码已完成 -->
    {% endblock main %}
    
    {% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">标题1</a>
            </li>
            <li>
                <a href="#">标题2</a>
            </li>
            <li>
                <a href="#">标题3</a>
            </li>
            <li>
                <a href="#">标题4</a>
            </li>
            <li>
                <a href="#">标题5</a>
            </li>
        </ul>
    </div>
    {% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <!--
                <span class="post-category"><a href="#">分类 {{ post.category.name }}</a></span>
                -->
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <!--
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                
                -->
                <span class="post-date"><a href="#"><time class="entry-date"
                    datetime="{{ post.created_time }}">{{ post.created_time|date:"Y-m-d" }}</time></a></span>
                <!--
                <span class="comments-link"><a href="#">4 评论</a></span>
                -->
                
                
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.body|truncatechars:54 }}</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
    <div class="no-post">not yet</div>
    {% endfor %}

    <!-- 简单分页效果-->
    {% if is_paginated %}
    <div class="pagination-simple">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
        <br/>
        <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.page_range }} 页</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    </div>
    {% endif %}
    
    <nav aria-label="Page navigation">
            <ul class="pagination">
              <li>
                <a href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li>
                <a href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock main %}